### ISSUE TITLE
Regarding the GitHub Organization "ViliOrg"

### ISSUE THREAD

**Issue by vil** [Sygmei/ViliData#25]
Hey,

I don't know if this "Vili" file format project is still maintained, but I'd recommend you, @Sygmei, to remove the url and contact info from the organizations description as I've had the ownership of the domain for almost 2 years now.

Otherwise visitors of this project will be lead to my website.

Thanks.

-Vili (@vil)

**Comment by Sygmei** [comment]
Got it, thanks for notifying me :)
